players:
  ItsKazzle:
    mode: 1
defaults:
  very_very_frightening: "adventure/very_very_frightening"
  complete_catalogue: "husbandry/complete_catalogue"
  all_effects: "nether/all_effects"
  kill_all_mobs: "adventure/kill_all_mobs"
  sniper_duel: "adventure/sniper_duel"
  uneasy_alliance: "nether/uneasy_alliance"
  ride_strider_in_overworld_lava: "nether/ride_strider_in_overworld_lava"
  froglights: "husbandry/froglights"
  summon_iron_golem: "adventure/summon_iron_golem"
  create_full_beacon: "nether/create_full_beacon"
  balanced_diet: "husbandry/balanced_diet"
descriptions:
  very_very_frightening:
    - " "
    - "§bAbilities:"
    - " "
    - "1. §lDash ability§r§b: Dash every 10 seconds."
  complete_catalogue:
    - " "
    - "§bPassives:"
    - "1. Luck I"
    - "2. No fall damage"
    - "3. 2 permanent hearts (until you lose the power)"
  all_effects:
    - " "
    - "§bAbilities:"
    - "1. §lDisable ability§r§b: Every 30s, disable a player's"
    - "   item for 3 seconds by shift-right clicking on a them."
    - "§bPassives:"
    - "1. §lPoison-Tipped Sword§r§b: A 1 in 20 chance to effect a player with a negative effect,"
    - "either Blindness, Wither, Weakness, or Slowness I."
    - "2. §lSword Blessing§r§b: A 1 in 30 chance to give yourself a positive effect, "
    - "   which contains all of the positive effects in the game."
  how_did_we_get_here?:
    - " "
    - "§bAbilities:"
    - "1. §lDisable ability§r§b: Every 30s, disable a player's"
    - "   item for 3 seconds by shift-right clicking on a them."
    - "§bPassives:"
    - "1. §lPoison-Tipped Sword§r§b: A 1 in 20 chance to effect a player with a negative effect,"
    - "either Blindness, Wither, Weakness, or Slowness I."
    - "2. §lSword Blessing§r§b: A 1 in 30 chance to give yourself a positive effect, "
    - "   which contains all of the positive effects in the game."
  kill_all_mobs:
    - " "
    - "§bAbilities:"
    - "1. §lDomain Expansion (ig)§r§b: A 14 block wide ice orb surrounds you for 5 seconds."
    - "   - You are given Resistance I while inside of the orb."
  sniper_duel:
    - " "
    - "§bAbilities:"
    - "1. §lSniper Vision§r§b: your vision allows you to apply"
    - "   Glowing I and Weakness IV to anyone within a 25-block radius, and gives you"
    - "   Strength 2."
  uneasy_alliance:
    - " "
    - "§bAbilities:"
    - "1. §lInvisibility§r§b: Make yourself COMPLETELY invisible for 15 seconds."
  ride_strider_in_overworld_lava:
    - " "
    - "§bAbilities:"
    - "1. §lBlazed§r§b: a lightning strike gives you Strength II for 10 seconds."
  froglights:
    - "§bAbilities:"
    - "1. §lOdyssey Stealer§r§b: Steal a players currently enabled power for 2 minutes."
  summon_iron_golem:
    - "§bAbilities:"
    - "1. §lHired Help§r§b: Summon an iron golem that fights for you for 20 seconds."
  balanced_diet:
    - "§bAbilities:"
    - "1. §lStored Energy§r§b: Gives you Saturation II for 15 seconds and "
