players:
  ItsKazzle:
    mode: 1
defaults:
  very_very_frightening: "adventure/very_very_frightening"
  complete_catalogue: "husbandry/complete_catalogue"
  all_effects: "nether/all_effects"
  kill_all_mobs: "adventure/kill_all_mobs"
  sniper_duel: "adventure/sniper_duel"
  uneasy_alliance: "nether/uneasy_alliance"
  ride_strider_in_overworld_lava: "nether/ride_strider_in_overworld_lava"
  froglights: "husbandry/froglights"
  summon_iron_golem: "adventure/summon_iron_golem"
  create_full_beacon: "nether/create_full_beacon"
  balanced_diet: "husbandry/balanced_diet"
  dragon_egg: "end/dragon_egg"
  bullseye: "adventure/bullseye"
  charlis_odyssey: "events/charlis_odyssey"
  quaks_odyssey: "events/quaks_odyssey"
  fortnite_odyssey: "events/fortnite_odyssey"
descriptions:
  very_very_frightening:
    - " "
    - "§bAbilities:"
    - " "
    - "1. §lDash ability§r§b: Dash every 10 seconds."
    - "2. §lZeus Bolt§r§b: a lightning strike gives you Strength II and Speed II for 15 seconds."
  complete_catalogue:
    - " "
    - "§bAbilites:"
    - "1. §lPotion Stealer§r§b: Steal all of a targeted players status effects, positive"
    - "or negative."
    - " "
    - "§bPassives:"
    - "1. §lRechargeable Totem§r§b: You have an extra life, but maybe not 9 extra."
    - "2. No fall damage."
  all_effects:
    - " "
    - "§bAbilities:"
    - "1. §lDisable ability§r§b: Every 30s, disable a player's"
    - "   item for 5 seconds by shift-right clicking on a them."
    - " "
    - "§bPassives:"
    - "1. §lPoison-Tipped Sword§r§b: A 1 in 20 chance to effect a player with a negative effect,"
    - "either Blindness, Wither, Weakness, or Slowness I."
    - "2. §lSword Blessing§r§b: A 1 in 30 chance to give yourself a positive effect, "
    - "   which contains all of the positive effects in the game."
  how_did_we_get_here?:
    - " "
    - "§bAbilities:"
    - "1. §lDisable ability§r§b: Every 30s, disable a player's"
    - "   item for 5 seconds by shift-right clicking on a them."
    - "§bPassives:"
    - "1. §lPoison-Tipped Sword§r§b: A 1 in 20 chance to effect a player with a negative effect,"
    - "either Blindness, Wither, Weakness, or Slowness I."
    - "2. §lSword Blessing§r§b: A 1 in 30 chance to give yourself a positive effect, "
    - "   which contains all of the positive effects in the game."
  kill_all_mobs:
    - " "
    - "§bAbilities:"
    - "1. §lDomain Expansion §r§b: A 14 block wide ice orb surrounds you for 5 seconds."
    - "   - You are given Resistance I while inside of the orb."
    - "2. §lBlack Hole§r§b: You summon a black hole that does a minimum of 0.1 hearts "
    - "   and a maximum of 0.67 hearts per second for 5 seconds until it dissipates."
  sniper_duel:
    - " "
    - "§bAbilities:"
    - "1. §lSniper Vision§r§b: your vision allows you to apply"
    - "   Glowing I, slowness I, and Weakness IV to anyone within a 25-block radius, and gives you"
    - "   Strength 2."
  uneasy_alliance:
    - " "
    - "§bAbilities:"
    - "1. §lInvisibility§r§b: Make yourself COMPLETELY invisible for 20 seconds."
    - "2. §lFreeze Ray§r§b: Freeze a player for 5 seconds, doing 0.75 hearts every second."
  ride_strider_in_overworld_lava:
    - " "
    - "§bAbilities:"
    - "1. §lBlazed§r§b: The Blazes bless you with 15 seconds of Strength II and Regeneration II."
    - "2. §lDamage Link§r§b: the player you choose shares damage with you, so when you take damage,"
    - "   the chosen player does the exact same amount of damage."
    - " "
    - "§bPassives:"
    - "1. §lFire Aspect§r§b: you have a 25% chance to set someone on fire when attacking."
    -     (THIS ONLY WORKS WHEN IN BLAZED)
  froglights:
    - " "
    - "§bAbilities:"
    - "1. §lMimic§r§b: copy a players name and skin for 2 minutes."
    - "2. §lFrog Tongue§r§b: pull a player towards you, similar to a frog tongue."
  summon_iron_golem:
    - " "
    - "§bAbilities:"
    - "1. §lHired Help§r§b: Summon an iron golem that fights for you for 20 seconds."
  balanced_diet:
    - " "
    - "§bAbilities:"
    - "1. §lStored Energy§r§b: Gives you Saturation II for 20 seconds and Hunger 60 to all players in"
    - "   a 25 block radius."
    - " "
    - "§bPassives:"
    - "1. §lJuggernaut§r§b: Eating a Glistering Melon gives you increased size, reach, and attack speed"
    - "   for 20 seconds."
  dragon_egg:
    - "§bAbilities:"
    - "1. §lGround Pound§r§b: do a Ground Pound, summoning a damaging effect cloud and doing 4 hearts of"
    - "   damage to all players in range."
    - "2. §lElytra Flight§r§b: Launch yourself into the air, allowing you to fly for 5 seconds."
  create_full_beacon:
    - "§bAbilities:"
    - "1. §lRewind§r§b: Go back 3 seconds in time, restoring everything, including position, saturation"
    - "   details, location, and rotation."
    - "2. §lBeaconator§r§b: give yourself a random beacon effect."
