name: SimpleS5
version: '${project.version}'
main: kazzleinc.simples5.SimpleS5
api-version: '1.20'
description:
  "Super baller plugin the best server ever, Odyssey SMP."

softdepend: [ ProtocolLib ]

commands:
  reloadconfig:
    description: "Reloads the server config.yml."
    usage: "/reloadconfig"
  odyssey:
    description: "All things Odyssey related."
    usage: "/odyssey <withdraw|description|powers>"
    aliases:
      - "od"
  power1:
    usage: "I don't think you gotta power lmao, this message shouldn't show"
  power2:
    usage: "I don't think you gotta power lmao, this message shouldn't show"
  resetcooldowns:
    usage: "/resetcooldowns"
    description: "resets the cooldowns of your enabled powers."
    aliases:
      - "rc"
  skin:
    usage: "baller"
  toggle-pvp:
    usage: "/toggle-pvp"
    description: "Opped players can enable or disable PvP."